In [5]:
import torch
from torch import nn

In [6]:
linear_layer = nn.Linear(
    in_features = 3,
    out_features = 2
)

In [7]:
inputs = torch.tensor([1.2, 2.3, 4])

In [11]:
out_puts = linear_layer(inputs)

In [12]:
out_puts

tensor([-1.4641,  1.6876], grad_fn=<ViewBackward0>)

In [13]:
linear_layer.bias

Parameter containing:
tensor([ 0.5509, -0.2360], requires_grad=True)

In [15]:
linear_layer.weight

Parameter containing:
tensor([[-0.3030, -0.2785, -0.2527],
        [-0.4062,  0.2884,  0.4369]], requires_grad=True)